### ISSUE TITLE
images not showing on brave browser

### ISSUE THREAD

**Issue by jcstein** [suntzu93/celestia-nft-mint#1]
<img width="1549" alt="scrot 2023-04-20 at 3 08 30 PM" src="https://user-images.githubusercontent.com/46639943/233464072-abbaaa74-c7cc-4f37-9abe-285f7e5d419c.png">

**Comment by suntzu93** [comment]
Thank you for reporting, fixed at https://github.com/suntzu93/celestia-nft-mint/commit/1da08188c754feb42b9d9c3c96c93588ad0cfbd9

**Comment by jcstein** [comment]
you're welcome! great work 🎉
